export const ADD_TASK_REQUEST="ADD_TASK_REQUEST"
export const ADD_TASK_SUCCESS="ADD_TASK_SUCCESS"
export const ADD_TASK_FAIL="ADD_TASK_FAIL"

export const DELETE_TASK_REQUEST="DELETE_TASK_REQUEST"
export const DELETE_TASK_SUCCESS="DELETE_TASK_SUCCESS"
export const DELETE_TASK_FAIL="DELETE_TASK_FAIL"

export const UPDATE_TASK_REQUEST="UPDATE_TASK_REQUEST"
export const UPDATE_TASK_SUCCESS="UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_FAIL="UPDATE_TASK_FAIL"

export const TODO_LIST_REQUEST ="TODO_LIST_REQUEST"
export const TODO_LIST_SUCCESS ="TODO_LIST_SUCCESS"
export const TODO_LIST_FAIL ="TODO_LIST_FAIL"

export const TODO_LIST ="TODO_LIST"

export const INVERSE_MARK_REQUEST="INVERSE_MARK_REQUEST"
export const INVERSE_MARK_SUCCESS="INVERSE_MARK_SUCCESS"
export const INVERSE_MARK_FAIL="INVERSE_MARK_FAIL"


export const CLEAR_SUCCESS_MESSAGE="CLEAR_SUCCESS_MESSAGE"





export const CHANGE_MODE="CHANGE_MODE"